name: Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Setup npm"
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap

      - name: Run tests
        run: npx lerna exec npm run test
