name: Checks

on: push


jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Login into docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   

      - name: generate config folder
        run:  npm run trusty-generate

      - name: Start blockchain-nodes
        run: |
          docker network create test-network
          cd ./config
          ./all.sh up -d
          ./initNodes.sh

          
      - name: "Setup npm"
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Cache node modules
        uses: actions/cache@v2
        id: node-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm i
          ./build.sh

      - name: Start trustcreator and platform services
        run: |
          cd test
          docker-compose up -d
          sleep 20

      - name: Run tests
        run: npm run test
